sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.21.2

services:
  - docker

before_install:
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose -f docker-compose.builder.yaml build app
  - docker-compose -f docker-compose.builder.yaml run app ng build --prod
  - ls ./
  - ls ./docker/
  - ls ./docker/nginx
  - ls ./docker/nginx/dist
#  - docker-compose -f docker-compose.builder.yaml build nginx
#  - docker login -u="$DOCKER_HUB_USER" -p="$DOCKER_HUB_PASSWORD"
#  - docker tag frontend_nginx vasary/exam-frontend:{TRAVIS_BRANCH}
#  - docker push "$DOCKER_HUB_USER"/exam-frontend:{TRAVIS_BRANCH}