version: '3.2'

services:
  app:
    container_name: exam-app
    build: ./docker/node
    volumes:
        - ./:/app
    restart: always
    ports:
      - 80:80
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - exam-network
    command: npm run-script start

networks:
  exam-network:
    external: true
