version: '3.2'

services:
  nginx:
    container_name: exam-frontend
    build: ./docker/nginx

  app:
    build: ./docker/node
    volumes:
        - ./:/app
    ulimits:
      nofile:
        soft: 65535
        hard: 65535